import Head from 'next/head';
import { NextPage, GetStaticProps } from 'next';

import { getAllFilesFrontMatter } from '../lib/mdx';

type Props = {
  posts: {
    title: string
    slug: string
    image: string
  }[] // los corchetes indican que es un array
}

const Home: NextPage<Props> = ({posts}) =>{
  return (
    <div className="container px-5 mx-auto">
      <Head>
        <title>Mi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8">
        {posts.map((post) =>(
          <article key={post.slug}>
            <h3>{post.title}</h3>
          </article>
        ))}
      </main>

      <footer>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Hecho en casa
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = await getAllFilesFrontMatter("posts");

  return {
    props: {
      posts
    }
  }
}

export default Home;
