import Head from 'next/head';
import { NextPage, GetStaticProps } from 'next';

import Link from '../components/Link';

import { getAllFilesFrontMatter } from '../lib/mdx';

type Props = {
  posts: {
    title: string
    slug: string
    image: string
  }[] // los corchetes indican que es un array
}

const Home: NextPage<Props> = ({posts}) =>{
  return (
    <div className="container px-5 mx-auto">
      <Head>
        <title>Mi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-8 space-y-4">
        {posts.map((post) =>(
          <Link 
            href={`/blog/${post.slug}`} 
            key={post.slug} 
            className='block rounded border border-gray-200 p-4 hover:bg-gray-300'
          >
            <h3>{post.title}</h3>
          </Link>
        ))}
      </main>

      <footer>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Hecho en casa
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = await getAllFilesFrontMatter("posts");

  return {
    props: {
      posts
    }
  }
}

export default Home;
